# Generated by Django 4.2.13 on 2026-05-29 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PopularDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='popular_images/')),
            ],
            options={
                'verbose_name': 'Popular Dish',
                'verbose_name_plural': 'Popular Dishes',
                'db_table': 'popular_dishes',
            },
        ),
        migrations.CreateModel(
            name='MenuDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='menu_images/')),
                ('category', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category')),
            ],
            options={
                'db_table': 'menu_dishes',
                'ordering': ['category', 'name'],
            },
        ),
    ]
